apiVersion: v1
kind: Pod
metadata:
  name: ippr
  namespace: ippr
  labels:
    app: ippr
spec:
  serviceAccountName: ippr
  containers:
  - name: ippr
    image: us-docker.pkg.dev/mofilabs/kubecon/ippr:v0.0.6
    ports:
    - containerPort: 8080
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        cpu: "500m"
        memory: "512Mi"
